# Generated by Django 3.0.7 on 2020-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_test', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_data',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
