# Generated by Django 3.0.7 on 2020-06-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_test', '0003_comments_comment_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('fk_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_test.Comments')),
            ],
        ),
    ]
