# Generated by Django 3.0.7 on 2020-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_test', '0004_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
