# Generated by Django 3.0.7 on 2020-06-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_test', '0005_auto_20200611_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='id_data',
            new_name='UserId',
        ),
    ]
