# Generated by Django 3.0.7 on 2020-06-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_test', '0007_auto_20200611_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(default='', max_length=50)),
                ('Follow_check', models.BooleanField(default=False)),
                ('FollowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_test.Comments')),
            ],
        ),
    ]
