# Generated by Django 3.0.7 on 2020-06-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_test', '0010_auto_20200611_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_test.Users'),
        ),
    ]
