# Generated by Django 3.0.7 on 2020-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_test', '0012_auto_20200612_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
